export const productsData = [
    {
      id: 1,
      sku: 18644119330491312,
      title: "Easily packable furniture",
      quantity: 1,
      type: "second",
      description: "IKEA - easily packable furniture for urban nomads",
      availableSizes: ["beds"],
      price: 10,
      img:"https://assets.newatlas.com/dims4/default/fca23ce/2147483647/strip/true/crop/1620x1080+150+0/resize/1200x800!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2Farchive%2Fravaror-2.jpg",
      isFreeShipping: true,
      isLiked: false,
    },
  
    {
      id: 2,
      sku: 11854078013954528,
      title: "STURSK",
      quantity: 1,
      type: "new",
      description: "Wall clock, black26 cm, 10 ¼",
      availableSizes: ["clocks"],
      price: 19.00,
      img:"https://www.ikea.com/us/en/images/products/stursk-wall-clock-black__0661138_pe711345_s5.jpg?f=s",
      isFreeShipping: true,
      isLiked: false,
    },
  
    {
      id: 3,
      sku: 876661122392077,
      title: "BRIMNES",
      quantity: 1,
      type: "second",
      description: " Desk, white, 120x65 cm",
      availableSizes: ["desks"],
      price: 65.0,
      img:"https://www.ikea.com/ie/en/images/products/brimnes-desk-white__0926236_pe789116_s5.jpg?f=s",
      isFreeShipping: true,
      isLiked: false,
    },
  
    {
      id: 4,
      sku: 9197907543445677,
      title: "STRANDMON",
      quantity: 1,
      type: "new",
      description: "Footstool, Skiftebo yellow",
      availableSizes: ["chairs"],
      price: 99.5,
      img:"https://www.ikea.com/eg/en/images/products/strandmon-footstool-skiftebo-yellow__0837297_pe601176_s5.jpg",
      isFreeShipping: false,
      isLiked: false,
    },
  
    {
      id: 5,
      sku: 10547961582846888,
      title: "BRIMNES",
      quantity: 1,
      type: "second",
      description: "Cabinet with doors, black30 3/4x37 3/8 ",
      availableSizes: ["cabinets"],
      price: 79.00,
      img:"https://www.ikea.com/us/en/images/products/brimnes-cabinet-with-doors-black__0705262_pe725488_s5.jpg?f=s",
      isFreeShipping: false,
      isLiked: false,
    },
  
    {
      id: 6,
      sku: 6090484789343891,
      title: "TÄRENDÖ / ADDE",
      quantity: 1,
      type: "new",
      description: "Table and 4 chairs, black, 110 cm",
      availableSizes: ["tables"],
      price: 23.5,
      img:"https://www.ikea.com/kw/en/images/products/taerendoe-adde-table-and-4-chairs-black__0732110_pe738573_s5.jpg?f=s",
      isFreeShipping: false,
      isLiked: false,
    },
  
    {
      id: 7,
      sku: 18532669286405342,
      title: "MALM",
      quantity: 1,
      type: "second",
      description: "Chest of 6 drawers, white160x78 cm",
      availableSizes: ["chests"],
      style: "Preto com listras brancas",
      price: 229.5,
      img:"https://www.ikea.com/au/en/images/products/malm-chest-of-6-drawers-white__0859014_pe624334_s5.jpg",
      isFreeShipping: true,
      isLiked: false,
    },
  
    {
      id: 8,
      sku: 5619496040738316,
      title: "ROTBLÖTA",
      quantity: 1,
      type: "new",
      description: "Wall clock - ash veneer/light gray 16 ½",
      availableSizes: ["clocks"],
      style: "Azul escuro",
      price: 18.7,
      img:"https://www.ikea.com/us/en/images/products/rotbloeta-wall-clock-ash-veneer-light-gray__0752493_pe747444_s5.jpg",
      isFreeShipping: false,
      isLiked: false,
    },
    {
      id: 9,
      sku: 11600983276356165,
      title: "BRIMNES",
      quantity: 1,
      type: "second",
      description: "Bed frame with storage, black/Luröy, Full",
      availableSizes: ["beds"],
      price: 134.9,
      img:"https://www.ikea.com/us/en/images/products/brimnes-bed-frame-with-storage-black-luroey__0949177_pe799533_s5.jpg?f=s",
      isFreeShipping: true,
      isLiked: false,
    },
  ];
  